import '../styles/globals.scss'
import Head from 'next/head'
import { PersistGate } from 'redux-persist/integration/react'
import { Provider } from 'react-redux'
import persistStore from 'redux-persist/lib/persistStore'
import store from '../store/index'

const persistor = persistStore(store)

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Provider store={store}>
        <PersistGate loading={'Loading.....'} persistor={persistor}>
        <Component {...pageProps} />
        </PersistGate>
      </Provider>
    </>
  )
}
